sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 8555dbb6742db91392fad7b016d2d05e298b476e
  keep-history: true
  on:
    branch: master
  local-dir: public